language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
matrix:
  exclude:
    - rvm: 2.2.2
      gemfile: gemfiles/rails_3.gemfile
before_install:
  - gem install bundler
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: 88c5452d41835351d037ce45781e2e88b1c0bdc8508ee9722746bac633bba88e